### ISSUE TITLE
Support Alexandrite

### ISSUE THREAD

**Issue by dtantono** [cynber/lemmy-instance-assistant#14]
Alexandrite is nice desktop web app that possess modern look compared to default lemmy. So, is it possible to make this extension integrate with alexandrite? So, we can search community easier

https://github.com/sheodox/alexandrite

**Comment by cynber** [comment]
I'll see what I can do :)

**Comment by cynber** [comment]
has been implemented, will be in next update

**Comment by cynber** [comment]
new version is out :)
